### PR TITLE
Add support for python 3.x

### PR DESCRIPTION
**Pull request by MrOutis**
- Remove built-in function: long()
- Change unicode() to str()

### CODE REVIEW

**Comment by MrOutis** [comment]
I guess this will just move the library from 2.x to 3.x, without  supporting 2.x :confused:

**Comment by dezhin** [comment]
Is it possible to keep python 2.x support in this PR?

**Comment by MrOutis** [comment]
I found this: http://python3porting.com/noconv.html

Let me try to support both

**Comment by MrOutis** [comment]
This should work :smile:

**Comment by dezhin** [comment]
I did it. Thank you for contribution.

**Pull request merged**
